In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import random, numpy, pandas
from  lightgbm import LGBMRegressor, LGBMClassifier, log_evaluation, early_stopping
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

def seed_everything(seed):
    np.random.seed(seed)
    random.seed(seed)
    
seed_everything(seed=2025)

In [2]:
from catboost import CatBoostRegressor ,Pool
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from sklearn.linear_model import ElasticNetCV, LassoCV, RidgeCV
from sklearn.svm import SVR

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import AdaBoostRegressor

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

from sklearn.pipeline import make_pipeline
from sklearn.model_selection import KFold, cross_val_score

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectFromModel

from sklearn.impute import SimpleImputer
import sklearn.linear_model as linear_model
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [3]:

def get_next_day(date_str):
    if date_str=='None':
        return 'None'
    date_obj = datetime.strptime(date_str, '%Y-%m-%d')
    previous_day = date_obj + timedelta(days=1)
    previous_day_str = previous_day.strftime('%Y-%m-%d')
    return previous_day_str

def get_feats(mode='train'):
    path=f'/kaggle/input/phems-hackathon-early-sepsis-prediction/{mode}ing_data/'
    
    print("< feats >")
    feats=pd.read_csv(path+f"SepsisLabel_{mode}.csv").drop_duplicates()
    #merge with other tables
    feats['measurement_datetime_day']=feats['measurement_datetime'].fillna('None').apply(lambda x:x[:10])

    print("< drug >")
    drug=pd.read_csv(path+f"drugsexposure_{mode}.csv")
    drug['measurement_datetime_day']=drug['drug_datetime_hourly'].fillna('None').apply(lambda x:x[:10])
    for col in ['drug_concept_id','route_concept_id']:
        drug[col]=drug[col].fillna('None').astype(str)
        group_df=drug.groupby(['person_id','measurement_datetime_day'])[col].apply(lambda x:" ".join(x)).reset_index()
        feats=feats.merge(group_df,on=['person_id','measurement_datetime_day'],how='left')
        feats[col]=feats[col].fillna('None')
    
    drug['measurement_datetime_day']=drug['measurement_datetime_day'].apply(lambda x:get_next_day(x))
    for col in ['drug_concept_id','route_concept_id']:
        group_df=drug.groupby(['person_id','measurement_datetime_day'])[col].apply(lambda x:" ".join(x)).reset_index().rename(columns={col:col+"previous_day"})
        feats=feats.merge(group_df,on=['person_id','measurement_datetime_day'],how='left')
        feats[col+"previous_day"]=feats[col+"previous_day"].fillna('None')
    
    feats['measurement_datetime']=pd.to_datetime(feats['measurement_datetime'])
    feats['dow']=feats['measurement_datetime'].dt.dayofweek
    feats['doy']=feats['measurement_datetime'].dt.dayofyear
    feats['hour']=feats['measurement_datetime'].dt.hour
    feats.drop(['measurement_datetime'],axis=1,inplace=True)

    print("-"*30)
    return feats

train=get_feats(mode='train')
test=get_feats(mode='test')
print(train.shape,test.shape)

< feats >
< drug >
------------------------------
< feats >
< drug >
------------------------------
(331639, 10) (130483, 9)

In [4]:
encoder = LabelEncoder()
#normalize = SimpleImputer(strategy='mean')

for i in zip(train.columns,train.dtypes):
    if i[1]=='O':
        train[i[0]] = train[i[0]].fillna('Unknown')
        train[i[0]]=encoder.fit_transform(train[i[0]].to_numpy().reshape(-1,1))
    else:
        train[i[0]] = train[i[0]].fillna(0)

for i in zip(test.columns,test.dtypes):
    if i[1]=='O':
        test[i[0]] = test[i[0]].fillna('Unknown')
        test[i[0]]=encoder.fit_transform(test[i[0]].to_numpy().reshape(-1,1))
    else:
        test[i[0]] = test[i[0]].fillna(0)

In [5]:
train_x = train.drop(columns=['SepsisLabel', 'person_id'])
train_y = train['SepsisLabel']

In [6]:
train.head()

,person_id,SepsisLabel,measurement_datetime_day,drug_concept_id,route_concept_id,drug_concept_idprevious_day,route_concept_idprevious_day,dow,doy,hour
0,274096387,0,2144,1521,81,1440,95,1.0,338.0,20.0
1,1719359031,0,1917,2760,1504,2638,1466,5.0,111.0,9.0
2,2024544816,0,906,2143,126,0,1000,2.0,195.0,7.0
3,213710896,0,1220,0,1019,7614,537,1.0,144.0,7.0
4,1335786468,0,2044,0,1019,0,1000,6.0,238.0,22.0

In [7]:
Fold=5
kf = KFold(n_splits=Fold)

cat_pre_test = numpy.zeros(len(test))

catboost = CatBoostRegressor(grow_policy='Depthwise',
                             iterations=1000,
                             eval_metric='RMSE',
                             random_state=0,
                             verbose=100)

for i, (train_index, test_index) in enumerate(kf.split(train)):

    print(f"FOLD: {i}")

    x_fold=train_x[train_index[0]: train_index[len(train_index)-1]]
    y_fold=train_y[train_index[0]: train_index[len(train_index)-1]]

    x_test_fold=train_x[test_index[0]: test_index[len(test_index)-1]]
    y_test_fold=train_y[test_index[0]: test_index[len(test_index)-1]]

    cat_features = list(train_x.select_dtypes(include=['object', 'category']).columns)
    
    train_pool = Pool(x_fold, y_fold, cat_features=cat_features)
    val_pool = Pool(x_test_fold, y_test_fold, cat_features=cat_features)
    
    #weight_ = weight[train_index[0]: train_index[len(train_index)-1]]
    
    catboost.fit(train_pool, eval_set=(val_pool), early_stopping_rounds=100)
    
cat_pre_test=catboost.predict(test)
print(catboost.score(x_test_fold, y_test_fold))

FOLD: 0
Learning rate set to 0.1223
0:	learn: 0.1361853	test: 0.1373926	best: 0.1373926 (0)	total: 114ms	remaining: 1m 54s
100:	learn: 0.0667069	test: 0.0705525	best: 0.0705525 (100)	total: 4.43s	remaining: 39.5s
200:	learn: 0.0526870	test: 0.0583728	best: 0.0583728 (200)	total: 8.67s	remaining: 34.5s
300:	learn: 0.0453600	test: 0.0520000	best: 0.0520000 (300)	total: 12.8s	remaining: 29.8s
400:	learn: 0.0404231	test: 0.0481593	best: 0.0481593 (400)	total: 17.1s	remaining: 25.5s
500:	learn: 0.0363240	test: 0.0449482	best: 0.0449482 (500)	total: 21.2s	remaining: 21.1s
600:	learn: 0.0335566	test: 0.0428260	best: 0.0428260 (600)	total: 25.4s	remaining: 16.9s
700:	learn: 0.0303745	test: 0.0402810	best: 0.0402810 (700)	total: 30.2s	remaining: 12.9s
800:	learn: 0.0281637	test: 0.0386848	best: 0.0386848 (800)	total: 34.6s	remaining: 8.58s
900:	learn: 0.0260956	test: 0.0370772	best: 0.0370772 (900)	total: 38.8s	remaining: 4.27s
999:	learn: 0.0248061	test: 0.0362199	best: 0.0362199 (999)	total: 43s	remaining: 0us

bestTest = 0.03621989241
bestIteration = 999

FOLD: 1
Learning rate set to 0.12666
0:	learn: 0.1361390	test: 0.1344822	best: 0.1344822 (0)	total: 69.6ms	remaining: 1m 9s
100:	learn: 0.0654070	test: 0.0634269	best: 0.0634269 (100)	total: 5.32s	remaining: 47.4s
200:	learn: 0.0525111	test: 0.0507419	best: 0.0507419 (200)	total: 10.3s	remaining: 41s
300:	learn: 0.0445927	test: 0.0430936	best: 0.0430936 (300)	total: 15.4s	remaining: 35.9s
400:	learn: 0.0397198	test: 0.0383848	best: 0.0383848 (400)	total: 21.2s	remaining: 31.7s
500:	learn: 0.0358396	test: 0.0347748	best: 0.0347748 (500)	total: 26.4s	remaining: 26.3s
600:	learn: 0.0326183	test: 0.0315607	best: 0.0315607 (600)	total: 31.4s	remaining: 20.9s
700:	learn: 0.0298836	test: 0.0289836	best: 0.0289836 (700)	total: 36.5s	remaining: 15.6s
800:	learn: 0.0277865	test: 0.0269741	best: 0.0269741 (800)	total: 41.5s	remaining: 10.3s
900:	learn: 0.0257487	test: 0.0249681	best: 0.0249681 (900)	total: 46.6s	remaining: 5.12s
999:	learn: 0.0244036	test: 0.0235342	best: 0.0235342 (999)	total: 52.3s	remaining: 0us

bestTest = 0.02353422618
bestIteration = 999

FOLD: 2
Learning rate set to 0.12666
0:	learn: 0.1361390	test: 0.1354398	best: 0.1354398 (0)	total: 71ms	remaining: 1m 10s
100:	learn: 0.0654070	test: 0.0655831	best: 0.0655831 (100)	total: 5.22s	remaining: 46.5s
200:	learn: 0.0525111	test: 0.0522492	best: 0.0522492 (200)	total: 10.2s	remaining: 40.7s
300:	learn: 0.0445927	test: 0.0441020	best: 0.0441020 (300)	total: 15.3s	remaining: 35.5s
400:	learn: 0.0397198	test: 0.0394083	best: 0.0394083 (400)	total: 20.3s	remaining: 30.4s
500:	learn: 0.0358396	test: 0.0355248	best: 0.0355248 (500)	total: 25.4s	remaining: 25.3s
600:	learn: 0.0326183	test: 0.0323072	best: 0.0323072 (600)	total: 30.9s	remaining: 20.5s
700:	learn: 0.0298836	test: 0.0296437	best: 0.0296437 (700)	total: 36.3s	remaining: 15.5s
800:	learn: 0.0277865	test: 0.0274976	best: 0.0274976 (800)	total: 41.4s	remaining: 10.3s
900:	learn: 0.0257487	test: 0.0255029	best: 0.0255029 (900)	total: 46.5s	remaining: 5.11s
999:	learn: 0.0244036	test: 0.0242102	best: 0.0242102 (999)	total: 51.6s	remaining: 0us

bestTest = 0.02421016925
bestIteration = 999

FOLD: 3
Learning rate set to 0.12666
0:	learn: 0.1361390	test: 0.1365858	best: 0.1365858 (0)	total: 59.4ms	remaining: 59.3s
100:	learn: 0.0654070	test: 0.0673581	best: 0.0673581 (100)	total: 5.24s	remaining: 46.6s
200:	learn: 0.0525111	test: 0.0544480	best: 0.0544480 (200)	total: 10.3s	remaining: 41s
300:	learn: 0.0445927	test: 0.0464629	best: 0.0464629 (300)	total: 16.1s	remaining: 37.4s
400:	learn: 0.0397198	test: 0.0414046	best: 0.0414046 (400)	total: 21.2s	remaining: 31.6s
500:	learn: 0.0358396	test: 0.0375438	best: 0.0375438 (500)	total: 26.2s	remaining: 26.1s
600:	learn: 0.0326183	test: 0.0342408	best: 0.0342408 (600)	total: 31.4s	remaining: 20.8s
700:	learn: 0.0298836	test: 0.0313585	best: 0.0313585 (700)	total: 36.4s	remaining: 15.5s
800:	learn: 0.0277865	test: 0.0292804	best: 0.0292804 (800)	total: 41.5s	remaining: 10.3s
900:	learn: 0.0257487	test: 0.0270062	best: 0.0270062 (900)	total: 47.3s	remaining: 5.2s
999:	learn: 0.0244036	test: 0.0256994	best: 0.0256994 (999)	total: 52.4s	remaining: 0us

bestTest = 0.02569937013
bestIteration = 999

FOLD: 4
Learning rate set to 0.1223
0:	learn: 0.1362348	test: 0.1375593	best: 0.1375593 (0)	total: 46.7ms	remaining: 46.7s
100:	learn: 0.0672895	test: 0.0695284	best: 0.0695284 (100)	total: 4.33s	remaining: 38.5s
200:	learn: 0.0530556	test: 0.0568795	best: 0.0568795 (200)	total: 8.52s	remaining: 33.9s
300:	learn: 0.0458192	test: 0.0510044	best: 0.0510044 (300)	total: 12.6s	remaining: 29.4s
400:	learn: 0.0408947	test: 0.0472110	best: 0.0472110 (400)	total: 16.9s	remaining: 25.2s
500:	learn: 0.0367898	test: 0.0443368	best: 0.0443368 (500)	total: 21.1s	remaining: 21s
600:	learn: 0.0337558	test: 0.0420932	best: 0.0420932 (600)	total: 26s	remaining: 17.3s
700:	learn: 0.0311125	test: 0.0404027	best: 0.0404015 (699)	total: 30.2s	remaining: 12.9s
800:	learn: 0.0290075	test: 0.0389883	best: 0.0389883 (800)	total: 34.3s	remaining: 8.53s
900:	learn: 0.0267634	test: 0.0374604	best: 0.0374604 (900)	total: 38.6s	remaining: 4.24s
999:	learn: 0.0249661	test: 0.0363692	best: 0.0363692 (999)	total: 42.7s	remaining: 0us

bestTest = 0.03636921134
bestIteration = 999

0.9358943684042271

In [8]:
id = pandas.read_csv('/kaggle/input/phems-hackathon-early-sepsis-prediction/SepsisLabel_sample_submission.csv')['person_id_datetime']
test_predictions = (cat_pre_test)

In [9]:
test_predictions

array([-0.01079801, -0.04021932, -0.01394999, ..., -0.0171772 ,
       -0.00836685, -0.02226123])

In [10]:
submission = pandas.DataFrame({
    'ID': id.values,
    'prediction': test_predictions,
})
submission

                                    ID  prediction
0       1416048048_2021-03-25 10:00:00   -0.010798
1        280531880_2024-01-22 18:00:00   -0.040219
2       1127023302_2023-12-29 21:00:00   -0.013950
3       2065909112_2021-07-07 05:00:00    0.117998
4        264445818_2024-08-23 22:00:00   -0.052175
...                                ...         ...
130478  1968006557_2023-10-28 03:00:00    0.046132
130479  1511876642_2024-09-04 15:00:00    0.057043
130480  1844025915_2024-05-09 10:00:00   -0.017177
130481   264445818_2024-07-07 15:00:00   -0.008367
130482   964130903_2019-10-13 07:00:00   -0.022261

[130483 rows x 2 columns]

In [11]:
submission.to_csv('submission.csv', index = False)